title = "Harmony"
gitRepoUrl = "https://github.com/steamautomata/harmony"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.ico"

# From git:
organizationName = "SteamAutomata"
projectName = "Harmonny"
url = "https://steamautomata.github.io"
baseUrl = "/harmony"
tagline = "I don't know what is a tagline"

[footer]
style = "dark"
copyright = "Copyright © 2025 SteamAutomata. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "examples"

[[footer.links.items]]
label = "github"
href = "https://github.com/steamautomata/harmony"
